### ISSUE TITLE
getGame API

### ISSUE THREAD

**Issue by joesprankle** [waqasraza123/school-sports-system-apis-laravel#20]
opp_logo messed up , i fixed in database but need to tropubleshoot where this is happening "http:\/\/cms.repitsports.com\/uploads\/opponents\/http:\/\/cms.repitsports.com\/\/uploads\/opponents\/2507.png"

they are saying the following is missing if you want to start on it, waiting for detail but i imagine is arrays of photos, news and video tagged to game:
game_photos is null
game_news is missing
game_video is missing

**Comment by waqasraza123** [comment]
fixed
