### ISSUE TITLE
getSchdule API

### ISSUE THREAD

**Issue by joesprankle** [waqasraza123/school-sports-system-apis-laravel#22]
APP team is asking for a field 

Game_Type: 
We need parameters for Pre Game, Post Game based on time and date of game. See photo this helps them display data correctly in screen as it has both, top three are post game. Also asking to add day_of_week for on march 24th you see is a thursday. Can we calculate day of week from date somehow?

![thumbnail](https://cloud.githubusercontent.com/assets/192599/19178858/10a51e88-8c0c-11e6-8c45-d220318ece4c.jpg)

**Comment by waqasraza123** [comment]
fixed
