### ISSUE TITLE
Sponsors in drop downs can be empty in Roster add/edit

### ISSUE THREAD

**Issue by joesprankle** [waqasraza123/school-sports-system-apis-laravel#6]
May not always be sponsored, maybe add --Select-- as top option and if not specified dont save a sponsor

**Comment by 16talon** [comment]
Chaundhry I got one request for you. As I see you have done some js with ajax calls to show the current values selected for the edit roster. So if you could do that for the new 3 fields that were missing in edit(roster_advertiser,games_advertiser,news_advertiser) Thank you. I will push now the changes with that fields, so pull first.
